include:
  - project: 'thegateway/api'
    file: '/.gitlab-ci-template.yml'


.wheels:
  extends: .wheels
  before_script:
    - pip wheel -w dist marshmallow==3.0.0rc6


run-dynamorm-tests:
  stage: test
  script:
    - apt update
    # Has to be part of the same job as the tests because otherwise it's not installed on the same machine
    - apt install -y default-jre
    - mkdir ~/.aws
    - cp tests/samples/aws_credentials_for_ci ~/.aws/credentials
    - pytest

